version: "3.0"

services:
  kerio:
    container_name: kerio_vpn_proxy
    privileged: true
    cap_add:
      - NET_ADMIN
    image: jarri1999/kerio-client-vpn-proxy
    ports:
      - 8118:8118
    volumes:
      - ./kerio-kvc.conf:/etc/kerio-kvc.conf
